require: rubocop-rspec

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

AllCops:
    NewCops: enable

Metrics/MethodLength:
  Max: 15

Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
