# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  default:
    working_directory: ~/codebreaker
    description: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.1.0

caches:
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}

commands:
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop

  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle

jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
